Change recommended handling of missing CHANTYPES
ircdocs/modern-irc pull request #230
Opened 2024-02-11 17:13 UTC by slingamn

Formerly we recommended treating missing CHANTYPES as an empty string, i.e. no channel types. This switches to the recommendation in https://datatracker.ietf.org/doc/draft-brocklesby-irc-isupport/ to assume the RFC1459 default of `#&`.

2024-02-11 17:47 UTC, tommyrot requested changes

2024-02-11 17:47 UTC, tommyrot commented on _includes/modern-appendix.md
> +The value is OPTIONAL. If not specified by the server, clients SHOULD assume a value of `CHANTYPES=#&`, corresponding to the RFC1459 behavior.
```suggestion
The value is OPTIONAL and if not specified indicates that no channel types are supported. If the parameter is not advertised by the server, clients SHOULD assume a value of `CHANTYPES=#&`, corresponding to the RFC1459 behavior.
```

2024-02-11 17:47 UTC, tommyrot commented on _includes/modern-appendix.md
> +The value is OPTIONAL. If not specified by the server, clients SHOULD assume a value of `CHANTYPES=#&`, corresponding to the RFC1459 behavior.
Distinguish between completely omitting the paramater and not sending a value.

2024-02-11 21:37 UTC, emersion commented
There are probably others ISUPPORT tokens that should be switched to have their default set to the RFC value.

2024-02-22 17:04 UTC, delthas approved these changes

2024-02-22 17:47 UTC, merged